### ISSUE TITLE
Output of path to report contains one '/' to much

### ISSUE THREAD

**Issue by Tronde** [radarsymphony/timew-csv#4]
## What have I done today?

~~~
$ git clone https://github.com/radarsymphony/timew-csv.git
$ mv timew-csv/csv.sh extensions/ # Edit csv.sh to set XLSX_FILE="FALSE"
$ tw report :week csv
/home/tronde/.timewarrior/timew-reports//tronde-2022-05-16-log.csv
~~~

## What do I expect?

The script should output the correct path `/home/tronde/.timewarrior/timew-reports/tronde-2022-05-16-log.csv`.

## Thank you for this awesome extension!

Anyway, thank you very much for this extension! I appreciate your work creating an easy to use script that exactly match my needs.

**Comment by radarsymphony** [comment]
Thank you @Tronde for the feedback!

I'm glad you've found this extension useful. Let be know if you have any feature requests :)
