### ISSUE TITLE
RFE: Set default to 'XLSX_FILE="FALSE"'

### ISSUE THREAD

**Issue by Tronde** [radarsymphony/timew-csv#5]
Generating a XLSX file in addition to the CSV seems to be redundant though it's a nice additional functionality for sure. But I guess the main purpose of your extension is to create CSV files.

Setting the default to `XLSX_FILE="FALSE"` would make the dependency `soffice` obsolete and prevents an error at the first run. ;-)

What do you think about it?

**Comment by radarsymphony** [comment]
Hi @Tronde,

Thanks for your interest in this extension! My apologies for the delay in replying to this inquiry. 

Yes, I agree with you. The original purpose was to create CSVs. (A client wanted reports in XLSX instead, so I started creating both). But you're right, to keep with the originally stated intent of this script, the default should be to just create the CSV and then allow the additional feature to be added if the user wants it. I will make that change and create a release.
